### ISSUE TITLE
Tietokantaan oma taulu sprintille

### ISSUE THREAD

**Issue by imhlas** [Ohtuilmo/ohtuilmo#13]
Related to user story: **_Kirjautunut opiskelija pystyy kirjaamaan käyttämiänsä työtunteja_** #2

**Comment by miahro** [comment]
Muistin tueksi alustava skeema:
table "sprint"
-id (autom)
-alkupvm
-loppupvm
-sprintin nunero
-open (ehkä, vaihtoehtona lukitustieto täällä, tai sitten loppupvm:n mukaan tarkistetaan muualla)
-ryhmän id / numero (suoraan tähän tai liitostauluun)

**Comment by miahro** [comment]
open pois tästä (tarpeeton)
