### ISSUE TITLE
E2E-testien toimintaan saaminen uudelle repositoriolle

### ISSUE THREAD

**Issue by Regularmute** [Ohtuilmo/ohtuilmo#36]
## Hyväksymiskriteerit

* Olemassaolevat testit menevät läpi paikallisesti
* Muutokset mergetty ja hyväksytty mainiin
* Testit menevät läpi GitHub Actionsissa

**Comment by miahro** [comment]
Testeistä, jotka oli jo projektin alussa rikki on oma erillinen issue.
