### ISSUE TITLE
Käyttäjä voi tarkastella oman ryhmänsä tuntikirjanpitoon liittyviä statistiikoita

### ISSUE THREAD

**Issue by imhlas** [Ohtuilmo/ohtuilmo#82]
## Tasks

- [ ] [](url) #91 
- [ ] [](url) #21 
- [ ] [](url) #240

## Hyväksymiskriteerit

**Comment by mluukkai** [comment]
tämän pitää onnistua kaikille käyttäjäryhmille:
- opiskelija
- ohjaaja
- admin

ohjaajan/adminin tapauksessa näytetään oletusarvoisesti menossa olevan lukukauden ryhmä(t) mutta valittaessa myös päästävä tarkastelemaan edellisten lukukausien ryhmiä

**Comment by miahro** [comment]
Ohjaaja ja admin toiminnallisuus erotettu omaksi user storyksi #246
